name: Module 01 --- Check Ubuntu & macOS compilation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jobuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  |
            make re -C module01/ex00
    - name: ex01
      run: |
            make re -C module01/ex01
    - name: ex02
      run: |
            make re -C module01/ex02
    - name: ex03
      run:  |
            make re -C module01/ex03
    - name: ex04
      run: |
            make re -C module01/ex04
    - name: ex05
      run: |
            make re -C module01/ex05
    - name: ex06
      run: |
            make re -C module01/ex06
    - name: ex07
      run: |
            make re -C module01/ex07

  stevejobs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ex00
      run:  |
            make re -C module01/ex00
    - name: ex01
      run: |
            make re -C module01/ex01
    - name: ex02
      run: |
            make re -C module01/ex02
    - name: ex03
      run:  |
            make re -C module01/ex03
    - name: ex04
      run: |
            make re -C module01/ex04
    - name: ex05
      run: |
            make re -C module01/ex05
    - name: ex06
      run: |
            make re -C module01/ex06
    - name: ex07
      run: |
            make re -C module01/ex07
